name: checkout_payment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  flutter_credit_card: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
#    - assets/translation/
#    - assets/lottie/
#    - assets/icons/

  fonts:
    - family: cairo-extra-light
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200

    - family: cairo-light
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

    - family: cairo-regular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400

    - family: cairo-medium
      fonts:
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500

    - family: cairo-semi-bold
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600

    - family: cairo-bold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

    - family: cairo-extra-bold
      fonts:
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800

    - family: cairo-black
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900